name: CI/CD pipeline anomaly_detector

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      THRESHOLD_MULTIPLIER: 3
      WINDOW_SIZE: 60
      TRAIN_DATA_PATH: "sensor_data_train.csv"
      TEST_DATA_PATH: "sensor_data_test.csv"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: anomaly-detection:latest
          outputs: type=docker,dest=/tmp/docker-image.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/docker-image.tar
  run-container:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp/

      - name: Load Docker image
        run: |
          docker load --input /tmp/docker-image.tar

      - name: Run Docker container
        run: |
          docker run -e THRESHOLD_MULTIPLIER=${{ env.THRESHOLD_MULTIPLIER }} \
                     -e WINDOW_SIZE=${{ env.WINDOW_SIZE }} \
                     -e       TRAIN_DATA_PATH=${{ env.TRAIN_DATA_PATH }} \
                     -e       TEST_DATA_PATH = ${{env.TEST_DATA_PATH}} \
                     anomaly-detection:latest
